<?php

/**
 * @file
 * Misc (un)installation and update hooks.
 */

/**
 * Implements hook_install().
 */
function islandora_member_of_entailment_install($is_syncing) {
  /** @var \Drupal\islandora_member_of_entailment\Plugin\DatabaseAdapterManagerInterface $manager */
  $manager = \Drupal::service('plugin.manager.islandora_member_of_entailment.database_adapter');

  $plugin = $manager->getDatabaseAdapterPlugin();

  $plugin->schema();
  $plugin->rebuild();
}

/**
 * Implements hook_uninstall().
 */
function islandora_member_of_entailment_uninstall($is_syncing) {
  /** @var \Drupal\islandora_member_of_entailment\Plugin\DatabaseAdapterManagerInterface $manager */
  $manager = \Drupal::service('plugin.manager.islandora_member_of_entailment.database_adapter');

  $plugin = $manager->getDatabaseAdapterPlugin();

  $plugin->uninstallSchema();
}
