---
name: Code Linting
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Run CodeSniffer
        uses: discoverygarden/CodeSniffer@v1
        with:
          # XXX: tests are somewhat repetitive due to building similar node
          # hierarchies; however, to avoid excessive binding between things,
          # thinking it's better to leave them as-is.
          phpcpd-exclude: ./tests/src/Kernel
