---
name: PHPUnit Tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  PHPUnit:
    uses: discoverygarden/phpunit-action/.github/workflows/phpunit.yml@v1
    secrets: inherit
    with:
      composer_patches: |
        {
          "discoverygarden/islandora_test_support": {
            "AUCIR-198: Node bundle use": "https://patch-diff.githubusercontent.com/raw/discoverygarden/islandora_test_support/pull/6.patch"
          },
        }
